<? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<? $i = $this->indexStart; foreach ($this->results->getResults() as $current):
  $recordNumber = $this->results->getStartRecord()+$i-$this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="row result clearfix">
    <div class="hidden-xs col-sm-1 hidden-print<? if ($showCheckboxes): ?> checkbox<? endif; ?>">
      <label>
        <?=sprintf('%03d',$recordNumber)?>
      </label>
<? /*
      <?=str_replace('class="', 'class="label label-info ', $this->RDSIndexRecord($current)->getMedienicon())?>
*/ ?>
    </div>
    <?=$this->record($current)->getSearchResult('list')?>
  </div>
<? endforeach; ?>
