<?
if (isset($this->results)) {
    $list = $this->results->getListObject();
    $recordTotal = $this->results->getResultTotal();
}
$account = $this->auth()->getManager();
?>

<? if ($recordTotal > 0): ?>
	<h4 class="fav-action-title"><?=$this->transEsc('RDS_FAVLIST_MANAGE_ITEMS')?></h4>
  <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', array('idPrefix' => '', 'list' => isset($list) ? $list : null, 'account' => $this->account))?>
<? endif; ?>
  