<div class="hintbox">
    <div class="hintbox_title"><?=$this->transEsc("RDS_PLEASE_NOTE")?></div>
    <div class="hintbox_content">
        <div class="line">
            <?=$this->translate("RDS_INTER_LIBRARY_LOAN_QUESTION")?>
            <?=$this->translate("RDS_INTER_LIBRARY_LOAN_LINK")?>
        </div>
        <div class="line">
            <?=$this->translate("RDS_INTER_LIBRARY_LOAN_NOTE")?>
            <?=$this->translate("RDS_INTER_LIBRARY_LOAN_NOTE_LINK")?>
        </div>
    </div>
</div>
