<?
  $this->searchClassId = 'RDSIndex';
  $this->createHomeTabs = true;
  $this->layout()->navigation = $this->render('layout/navigation.phtml');
  $this->history = true;
?>

<?=$this->layout()->navigation ?>

<?
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li class="active">' . $this->transEsc('History') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <? if (!empty($this->saved)): ?>
      <h2><?=$this->transEsc("history_saved_searches")?></h2>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true));?>
    <? endif; ?>

    <h2><?=$this->transEsc("history_recent_searches")?></h2>
    <? if (!empty($this->unsaved)): ?>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false));?>
      <a href="?purge=true"><i class="fa fa-remove"></i> <?=$this->transEsc("history_purge")?></a>
    <? else: ?>
      <?=$this->transEsc("history_no_searches")?>
    <? endif; ?>
  </div>
</div>