<? 
if ($this->createHomeTabs == true) {
  $searchTabs = $this->searchtabs(null, null, null, null);
} else {
  $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType);
    foreach ($searchTabs as $id => $tab) {
        if ($tab['selected'] && isset($this->results))
            $searchTabs[$id]['resultCount'] = '(' . $this->results->getResultTotal() . ')';
        else {
            if (! empty($this->lookfor)) {
                $searchTabs[$id]['resultCount'] = '<span class="resultCountAjax" data-searchClassId="' . $tab['class'] . '" data-lookfor="' . htmlspecialchars($this->lookfor) . '"></span>';
            }
        }
    }
}
?>

<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
      <li<?=$tab['selected'] ? ' class="active"' : ''?>>
        <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
          <?=$this->transEsc($tab['label']); ?> <?=$tab['resultCount']; ?>
        </a>
      </li>
    <? endforeach; ?>
  </ul>
<? endif; ?>
