<? $locale = $this->plugin('translate')->getTranslator()->getLocale(); ?>

<h2>RDS_BIBLIOGRAPHIC_DETAILS</h2>

<?
    $informationItem = $this->rdsexport($this->driver, 'HTML')->getBibliographicDetails();
?>

<? foreach ($informationItem as $itemName => $itemValue): ?>
<h4><?=$itemName?></h4>
<?=$itemValue ?>
<? endforeach; ?>

<h2>RDS_CONTENT_DETAILS</h2>
<?
    $descriptionItems = $this->rdsexport($this->driver, 'HTML')->getDescription();
?>

<? foreach ($descriptionItems as $itemName => $itemValue): ?>
<h4><?=$itemName?></h4>
<?=$itemValue ?>
<? endforeach; ?>

<? 
    $holdings = $this->rdsexport($this->driver, 'HTML')->getHoldings();
?>
<? if ($holdings): ?>
<h2>RDS_HOLDINGS_INFOS</h2>
<? foreach ($holdings as $itemName => $itemValue): ?>
<h4><?=$itemName?></h4>
<?=$itemValue ?>
<? endforeach; ?>
<? endif; ?>

<!-- ?=$this->record($this->driver)->getTab(new VuFind\RecordTab\RDSProxyHoldings()) ?> -->