<input type="hidden" name="cachePolicy" value="Favorite" />
<? if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->id)?>" />
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->title)?>" />
<? endif; ?>
<? $user = $this->auth()->isLoggedIn(); ?>
<div class="checkbox">
    <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
    <?=$this->transEsc('RDS_SELECT_ALL_ITEMS')?>
</div>
<div class="btn-group">
  <span class="fa fa-envelope-o">
    <input class="bulk-link" type="submit" name="email" value="<?=$this->transEsc('RDS_EMAIL_SELECTION')?>" title="<?=$this->transEsc('RDS_EMAIL_SELECTION')?>"/>
  </span>
  <br />
  <? if ((!is_null($this->list) && $this->list->editAllowed($user)) || is_null($this->list) && $user): ?>
    <span class="fa fa-trash-o">
      <input class="bulk-link" id="<?=$this->idPrefix?>delete_list_items_<?=!is_null($this->list) ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="<?=$this->transEsc('RDS_DELETE_SELECTION')?>" title="<?=$this->transEsc('RDS_DELETE_SELECTION')?>"/>
    </span>
    <br />
  <? endif; ?>
  <? $exportOptions = $this->export()->getBulkOptions(); if (count($exportOptions) > 0): ?>
    <span class="fa fa-print">
      <input class="bulk-link" type="submit" name="export" value="<?=$this->transEsc('RDS_EXPORT_SELECTION')?>" title="<?=$this->transEsc('RDS_EXPORT_SELECTION')?>"/>
    </span>
    <br />    
  <? endif; ?>
  <span class="fa fa-external-link">
    <input class="bulk-link" type="submit" name="doExport" value="<?=$this->transEsc('RDS_PRINT_SELECTION')?>" title="<?=$this->transEsc('RDS_PRINT_SELECTION')?>"/>
  </span>
</div>