<?
  // Grab list object from search results (if applicable):
  $list = $this->results->getListObject();

  // Set up page title:
  $this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));

  // Set up breadcrumbs:
  $currPage = isset($list) ? 'List' : 'Favorites';
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc($currPage) . '</li>';

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption()!="full") {
     $this->headScript()->appendFile("full_view.js");
  }

  $recordTotal = $this->results->getResultTotal();

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();
  
  $this->createHomeTabs = true;
?>

<?=$this->flashmessages()?>

<nav class="nav searchbox hidden-print">

	<? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
  <?=$this->layout()->navigation ?>
</nav>
<div class="row">
  <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>">
  

  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="clearfix hidden-print">
    
      <h2 class="pull-left flip"><?=$list ? $this->escapeHtml($list->title) : $this->transEsc("Your Favorites")?> (<?=$recordTotal?>) </h2>
        
      <div class="fav-list-actions">
        <? if ($list && $list->editAllowed($account->isLoggedIn())): ?>
          <div class="btn-group">
            <a class="btn btn-link dropdown-toggle" title="<?=$this->transEsc("delete_list")?>" data-toggle="dropdown" href="<?=$this->url('myresearch-deletelist') ?>?listID=<?=urlencode($list->id)?>">
              <i class="fa fa-trash-o"></i>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<?=$this->url('myresearch-deletelist') ?>?listID=<?=urlencode($list->id)?>&amp;confirm=1"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
          <a href="<?=$this->url('editList', array('id' => $list->id)) ?>" class="btn btn-link" title="<?=$this->transEsc("edit_list")?>">
            <i class="fa fa-cog"></i>
          </a>
        <? endif; ?>
      </div>
    
    </div>
  <? if ($list && !empty($list->description)): ?>
    <p><?=$this->escapeHtml($list->description)?></p>
  <? endif; ?>
    <? if ($recordTotal > 0): ?>
      <div class="resulthead">
        <div class="pull-right flip">

        </div>
      </div>
        
        <div class="search-results-listing iterating-list">
        <? $i = $this->indexStart; foreach ($this->results->getResults() as $i=>$current): ?>
          <div id="result<?=$i++ ?>" class="row result clearfix">
            <?=$this->record($current)->getListEntry($list, $user)?>
          </div>
        
        <? endforeach; ?>
        </div>
        
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', array('results' => $this->results))?>
    <? else: ?>
      <div class="search-results-listing">
        <p><?=$this->transEsc('You do not have any saved resources')?></p>
      </div>
    <? endif; ?>
  </div>
  
  
  
  <div class="<?=$this->layoutClass('sidebar')?> sidebar-offset sidebar-fav-history">
      <a href="<?=$this->url('search-history')?>"><?=$this->transEsc('RDS_SEARCH_HISTORY_LINK_TITLE')?> <i class="fa fa-arrow-right"></i></a>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?> sidebar-offset sidebar-fav-admin">
    <?=$this->context($this)->renderInContext("myresearch/menu-fav-items.phtml", array('active' => isset($list) ? 'list' . $list['id'] : 'favorites'))?>
  </div>
  
  <div class="<?=$this->layoutClass('sidebar')?> sidebar-offset sidebar-fav-admin">
    <?=$this->context($this)->renderInContext("myresearch/menu-fav-lists.phtml", array('active' => isset($list) ? 'list' . $list['id'] : 'favorites'))?>
  </div>
  
  
  <div class="<?=$this->layoutClass('sidebar')?> sidebar-offset sidebar-fav-info">
    <h4><?=$this->transEsc('RDS_FAVLIST_INFO_TITLE')?></h4>
    <?=$this->transEsc('RDS_FAVLIST_INFO_CONTENT')?>
    
    <? foreach ($this->results->getRecommendations('side') as $current): ?>
      <?=$this->recommend($current)?>
    <? endforeach; ?>
  </div>



  </form>
</div>
