<?
  if ($this->searchType != 'advanced') {
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');
  }
    ?>

<div>

  <div class="rds_title">Katalog plus </div>

  <div class="rds_searchbox">
    <nav class="nav searchbox">
      <?=$this->layout()->searchbox ?>
    </nav>
  </div>

  <div class="rds_searchTabs">
      <?= $this->render('search/searchTabs'); ?>
  </div>

  <div class="rds_subnav">
        <ul>
            <?if (isset($this->searchType) && $this->searchType == 'advanced'):?>
            <li><a href="<?=$this->url('home') ?><?=$this->searchClassId ?>/Home"><?=$this->transEsc('RDS_BASIC_SEARCH')?></li>
            <?else:?>
            <li><a href="<?=$this->url('home') ?><?=$this->searchClassId ?>/Advanced"><?=$this->transEsc('RDS_ADVANCED_SEARCH')?></li>
            <? endif;?>
            <li><a href="<?=$this->url('home') ?>Search/History"><?=$this->transEsc('RDS_RDSHistory')?></a></li>
            
            <li>
            <?if ($this->auth()->isLoggedIn()): ?>
              <a href="<?=$this->url('myresearch-home') ?>?redirect=0"><?=$this->transEsc('RDS_RDSFavorites')?></a>
            <?else: ?>
              <? $cart = $this->cart(); if ($cart->isActive()): ?>
                <a id="cartItems" class="modal-link" title="<?=$this->transEsc('RDS_RDSFavorites')?>" href="<?=$this->url('cart-home')?>"><?=$this->transEsc('RDS_RDSFavorites')?> (<strong><?=count($cart->getItems())?></strong>)</a>
              <? endif; ?>
            <?endif; ?>
            </li>
        </ul>        
    </div>
  
  
</div>