<? if ($mobileViewLink = $this->mobileUrl()): // display 'return to mobile' link when applicable ?>
  <hr/>
  <div class="mobileViewLink"><a href="<?=$this->escapeHtml($mobileViewLink)?>"><?=$this->transEsc("mobile_link")?></a></div>
<? endif; ?>
<hr/>
<div class="span8 row-fluid small">
<!-- start footerWrapper -->
<div id="footerWrapper">
<div id="footer">
	
	<ul id="siteActions">
		<li>
			<a href="http://www.uni-ulm.de/einrichtungen/kiz/home/sitemap.html" target="_self">Sitemap</a>
		</li>
		<li>
			<a href="http://www.uni-ulm.de/einrichtungen/kiz/home/impressum.html" target="_self" title=" ">Impressum</a>
		</li>
	</ul>
	
</div>	
</div>
</div>
