<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }


  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
<?=$this->layout()->navigation ?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>" rel="nofollow">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>" rel="nofollow"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<? /*
<?=$this->record($this->driver)->getToolbar()?>
*/ ?>

<div class="row">
  <div class="col-sm-12">
    <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
<div class="panel-group" id="accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>">

  <? if (count($this->tabs) > 0): ?>
    <? foreach ($this->tabs as $tab => $obj): ?>
      <? if ($tab == 'HierarchyTree' || $tab == 'Similar' || $tab == 'Details') continue; ?>
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-target="#<?=(strtolower($tab))?>-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" style="cursor: pointer">
          <h4 class="panel-title">
            <a class="accordion-toogle">
              <?=$this->transEsc($obj->getDescription())?>
            </a>
          </h4>
        </div>
        <div id="<?=(strtolower($tab))?>-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse in">
          <div class="panel-body">
            <?=$this->record($this->driver)->getTab($obj) ?>
          </div>
        </div>
      </div>
    <? endforeach; ?>
  <? endif; ?>

  <? if ($this->related()->getList($this->driver) != null ): ?>
    <div class="panel panel-default">
      <div class="panel-heading" data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-target="#related-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" style="cursor: pointer">
        <h4 class="panel-title">
          <a class="accordion-toogle">
            <?=$this->transEsc("Related Items")?>
          </a>
        </h4>
      </div>
      <div id="related-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse in">
        <div class="panel-body">
          <? foreach ($this->related()->getList($this->driver) as $current): ?>
            <?=$this->related()->render($current)?>
          <? endforeach; ?>
        </div>
      </div>
    </div>
  <? endif; ?>

  <? $obj = $this->tabs['Details']; if ($obj): ?>
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-target="#<?=(strtolower($tab))?>-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" style="cursor: pointer">
          <h4 class="panel-title">
            <a class="accordion-toogle">
              <?=$this->transEsc($obj->getDescription())?>
            </a>
          </h4>
        </div>
        <div id="<?=(strtolower($tab))?>-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse in">
          <div class="panel-body">
            <?=$this->record($this->driver)->getTab($obj) ?>
          </div>
        </div>
      </div>
  <? endif; ?>

</div>
    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenURL()).'"></span>':''?>
  </div>

</div>
