<? $records = $this->cart()->getRecordDetails(); if (!empty($records)): ?>
  <hr/>
  <ul class="list-unstyled">
  <? foreach ($records as $i => $record): ?>
    <li>
      <div class="checkbox">
        <label>
          <?=$this->record($record)->getCheckbox('cart')?>
          <a title="<?=$this->transEsc('View Record')?>" href="<?=$this->recordLink()->getUrl($record)?>"><?=$this->escapeHtml($this->truncate($record->getBreadcrumb(),75))?></a> 
        </label>
        <? $breadcrumbMore = $record->getBreadcrumbMore(); ?>
        <? if (isset($breadcrumbMore)): ?>
          <div class="breadcrumbmore">
             <?=$breadcrumbMore?>
          </div>
        <? endif; ?>
      </div>
    </li>
  <? endforeach; ?>
  </ul>
<? else: ?>
  <? if(! $this->auth()->isLoggedIn()): ?>
      <p class="alert alert-info"><?=$this->transEsc('bookbag_is_empty')?>.</p>
  <? endif; ?>
<? endif; ?>
