<?
    // Set page title.
    $this->headTitle($this->translate('RDSIndexDescription') . ': ' . $this->driver->getBreadcrumb());

    // Grab clean ISBN for convenience:
    $isbn = $this->driver->getCleanISBN();
     $description = $this->RDSIndexDescription($this->driver)->getItems();
?>
<? foreach ($description as $bib_key => $bibdescription): ?>

	<table class="table table-striped" >
		<tr>
		<th><?= $this->translate($bib_key) ?> </th>
		<td>
			<?= $bibdescription ?>
		</td>
		</tr>
	</table>
<? endforeach; /* end foreach description */ ?>


