<?
    // Set page title.
    $this->headTitle($this->translate('Bibliograhic Detials') . ': ' . $this->driver->getBreadcrumb());
    $coreItems = $this->rdsindexcore($this->driver)->getItems();
?>
<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">
 <tbody> 
    <? foreach ($coreItems as $itemName => $itemValue): ?>
    <? $contentDisplayed = true; ?>
    <tr class="<?=$itemName?>">
      <th><?=$this->translate($itemName)?>: </th>
      <td colspan="3">
          <?=$itemValue?><br/>
      </td>
    </tr>
    <? endforeach; ?>
  
  <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <? endif; ?>
 </tbody> 
</table>
