<?
  $proxyHelper = $this->RDSProxyHoldings();
  $fulltextLinks = $this->driver->getFulltextLinks();
  $infoLinks = $this->driver->getInfoLinks();

  if ($fulltextLinks && count($fulltextLinks) == 1 && $fulltextLinks[0]['indicator'] == 2) {
    $fulltextLinks = '';
  }
  $authManager = $this->auth()->getManager();
  $sessionInitiator = $authManager->getSessionInitiator($this->serverUrl($this->url('myresearch-home')));
  if ($sessionInitiator) {
    $loginLink = $this->escapeHtmlAttr($sessionInitiator);
  } else {
    $loginLink = $this->url('myresearch-userlogin');
  }
?>

<?if ($proxyHelper->isFulltextView()): ?>
  <?if ($fulltextLinks || $infoLinks): ?>
    <div class="tg">
      <h2><?=$this->transEsc("RDS_ELECTRONTIC_FULLTEXT")?></h2>
      
      <?if ($fulltextLinks): ?>
        <?foreach ($fulltextLinks as $fulltextLink): ?>
            
            <?if ($fulltextLink['indicator'] == 1):?>
              <?if ($this->auth()->isLoggedIn() === false):?>
                <span class="t_ezb_yellow"></span>
                <a style="text-decoration: none;" href='<?=$loginLink ?>'; return false;">
                    <?=$this->transEsc("RDS_PROXY_PDF_FULLTEXT")?> (via <?=$fulltextLink['provider']?>) <?=$this->transEsc("RDS_PROXY_HOLDINGS_FOR_AUTHORIZED_USERS_ONLY")?>
                </a>
              <?elseif ($this->driver->getGuestView() == 'brief'):?>
                <span class="t_ezb_yellow"></span>
                <?=$this->transEsc("RDS_PROXY_PDF_FULLTEXT")?> (via <?=$fulltextLink['provider']?>) - <?=$this->transEsc("RDS_PROXY_FOR_AUTHORIZED_USERS_ONLY")?>
              <?endif;?>
            <?elseif ($fulltextLink['indicator'] != 2):?>
                <div class="t_ezb_result">
                  <p>
                      <?if ($fulltextLink['type'] == "pdf"):?>
                        <span class="t_ezb_yellow"></span>
                        <?=$this->transEsc("RDS_PROXY_PDF_FULLTEXT")?> (via <?=$fulltextLink['provider']?>)
                      <?endif;?>
                      <?if ($fulltextLink['type'] == "html"):?>
                        <span class="t_ezb_yellow"></span>
                        <?=$this->transEsc("RDS_PROXY_HTML_FULLTEXT")?> (via <?=$fulltextLink['provider']?>)
                      <?endif;?>
                      <?if ($fulltextLink['type'] == "external"):?>
                        <span class="t_ezb_{$fulltextLink.access}"></span>
                        <?=$this->transEsc("RDS_PROXY_TO_THE_FULLTEXT")?> (via <?=$fulltextLink['provider']?>)
                      <?endif;?>
                    <span class="t_link"><a target="_blank" href="<?=$fulltextLink['url']?>">&#187;</a></span>
                  </p>
                </div>
              <?endif;?>
              
        <?endforeach; ?>
      <?endif; ?>
      
      <?if ($infoLinks): ?>
        <?foreach ($infoLinks as $infoLink): ?>
          <div class="t_ezb_result">
            <p>
              <span class="t_ezb_<?$infoLink['access'] ?>"></span>
              <?=$this->transEsc("RDS_LINKS_INFO_" . strtoupper($infoLink[info]))?>
              <span class="t_link"><a target="_blank" href="<?=$infoLink['url'] ?>">&#187;</a></span>
            </p>
          </div>
        <?endforeach; ?>
      <?endif; ?>
    </div>
  <?endif; ?>

  <?if ($proxyHelper->isLinkresolverView() && (!empty($fulltextLinks) || !empty($infoLinks))):?>
    <div class="tg">
      <h2><?=$this->transEsc("RDS_PROXY_MORE_SOURCES")?></h2>
      <p>
        <a class="redi_links_icon" target="linkresolver" href="<?=$this->driver->getOpenUrlExternal();?>" title="<?=$this->transEsc("RDS_PROXY_REDI_LINKS")?>"></a>
      </p>
    </div>
  <?endif;?>

<?endif; ?>

<div>
<?if (!$proxyHelper->isFulltextView() || (empty($fulltextLinks) && empty($infoLinks))):?>
  <?=$proxyHelper->getServicesHTML($this->driver->getOpenUrlExternal()) ?>
<?endif; ?>
</div>
