<?
    // Set page title.
    $this->headTitle($this->translate('Bibliograhic Detials') . ': ' . $this->driver->getBreadcrumb());
    $coreItems = $this->rdsproxycore($this->driver)->getItems();
?>
<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">
  
    <? foreach ($coreItems as $itemName => $itemValue): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc($itemName)?>: </th>
      <td>
          <?=$itemValue?><br/>
      </td>
    </tr>
    <? endforeach; ?>
  
  <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <? endif; ?>
</table>