<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->renderSearchbox = false;
  
  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
      // Not an advanced query -- ignore it.
      $searchDetails = $groups = false;
    } else {
      $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();

    $searchTerms = [];
  
    $queries = $searchDetails->getQueries()[0]->getQueries();
    foreach ($queries as $query) {
      $searchTerms[$query->getHandler()] = $query->getString();
    }
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
  }
  
  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'RDSIndex';
  }

  $this->searchType = 'advanced';
  
  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->renderSearchbox = true;
  if (!isset($this->layout()->renderSearchbox) || $this->layout()->renderSearchbox != false) {
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');
  }
  
?>

<div>

  <? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
  <?=$this->layout()->navigation ?>

  <?=$this->flashmessages()?>
  <form role="search" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
  <div class="row">
    <div class="<?=$this->layoutClass('mainbody')?>">

      <div class="advSearch"><?=$this->transEsc("RDS_ADVANCED_SEARCH")?></div>

      <div id="group0" class="group well row">
	<input type="hidden" name="join" value="AND">	
	<div class="col-md-12">
           <div class="row">
      	       <? $counter = 0; ?>
	       <?foreach ($this->options->getAdvancedHandlers() as $key => $value):?>
                  <div class="search" id="search0_<?=$counter?>">
        	     <div class="row">
          		<div class="col-md-4">
                            <?=$this->transEsc($value)?>
                            <input type="hidden" value="<?=$key?>" name="type0[]" />
          	        </div>
 			<div class="col-md-8">
                           <? if ($key=="au" || $key=="co" || $key=="ct" || $key=="si"): ?>
                              <span>
                               <input id="search_lookfor0_<?=$key?>" onfocus="myhelp('<?=$this->transEsc("RDS_B_" . $key . "_help_head")?>','<?=$this->transEsc("RDS_B_" . $key . "_help_text")?>');" class="form-control" type="text" name="lookfor0[]" value="<? if(isset($searchTerms[$key])) {echo $searchTerms[$key];}?>">
                               <span class="index">
                               <a href="<?=$this->url('alphabrowse-home')?>?source=<?=$this->transEsc('register_' . $key)?>&amp;from=" onclick="this.href+=document.getElementById('search_lookfor0_<?=$key?>').value"><span class="reg_button" title="Indexsuche">Index</span></a>
                               </span>
                              </span>
                          <? else: ?>
                             <span>
        			<input id="search_lookfor0_<?=$key?>" class="form-control" onfocus="myhelp('<?=$this->transEsc("RDS_B_" . $key . "_help_head")?>','<?=$this->transEsc("RDS_B_" . $key . "_help_text")?>');" type="text" name="lookfor0[]" value="<? if(isset($searchTerms[$key])) {echo $searchTerms[$key];}?>">
                             </span>
                          <? endif; ?>
          	       </div>
                       <input type="hidden" name="bool0[]" value="AND">
                    </div>
      		</div>
             <? endforeach; ?>
          </div>
       </div>    				
  
    </div>

    <input class="btn btn-primary pull-right" type="submit" value="<?= $this->transEsc('RDS_SEARCH')?>">

    <div class="btn btn-primary pull-right">
           <a href="<?=$this->url($this->options->getAdvancedSearchAction())?>"><?=$this->transEsc("RDS_REMOVE_SEARCH_TERMS")?></a> 
    </div>

  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">

    <? /* add Search-History and Favorites to sidebar */ ?>
    <ul>

            <?if ($this->auth()->isLoggedIn()): ?>
                <li><a href="<?=$this->url('myresearch-home') ?>"><?=$this->transEsc('RDS_RDSFavorites')?></a></li>
            <?else: ?>
                <? $cart = $this->cart(); if ($cart->isActive()): ?>
                  <li id="cartSummary">
                    <a id="cartItems" class="modal-link" title="<?=$this->transEsc('RDS_RDSFavorites')?>" href="<?=$this->url('cart-home')?>"><?=$this->transEsc('RDS_RDSFavorites')?> (<strong><?=count($cart->getItems())?></strong>)</a>
                  </li>
                <? endif; ?>
             <?endif; ?>

           <li><a href="<?=$this->url('home') ?>Search/History"><?=$this->transEsc('RDS_RDSHistory')?></a></li>
    </ul>

    <div class="sidegroup">
      <div id="searchTipps">
        <div id="tippHeader"></div>
        <div id="tippBody"></div>
      </div>
    </div>
  </div>
</form>
	
  <div class="row">
  <form method="get" action="<?=$this->url($this->options->getSearchAction())?>" id="expadvSearchForm" name="exsearchForm" class="search">

    <div class="expSearch col-md-8">
       <?=$this->transEsc("RDS_EX")?>
       <a class="help" href="{translate text="RDS_EXPERT_SEARCH_HELP_URL"}">[?]</a>
    </div>

    <div class="expSearchContent col-md-8">
      <div class="groupSearchHolder">
           <div class="expRow">
             <input type="hidden" name="join" value="AND">
             <input type="hidden" value="ex" name="type0[]" />
             <input id="search_lookfor_ex" type="text" 
                    value="<? if(isset($searchTerms["ex"])) {echo $searchTerms["ex"];}?>" 
                    onfocus="myhelp('<?=$this->transEsc("RDS_B_ex_help_head")?>','<?=$this->transEsc("RDS_B_ex_help_text")?>');"
                    size="50" name="lookfor0[]"/>
              <input type="hidden" name="bool0[]" value="AND">
              <input class="btn btn-primary pull-right" type="submit" value="<?= $this->transEsc('RDS_SEARCH')?>">
           </div>
      </div>
    </div>
  </form>

  </div>



</div>
