    <div class="row">
      <div class="footer-left col-sm-6 col-md-4 col-lg-6">
        <ul class="list-unstyled">
          <li> <a href="https://hoh.ibs-bw.de/aDISWeb/app?service=direct/0/Home/$DirectLink&sp=S127.0.0.1:23022&sp=SBK00000000"><?=$this->transEsc('RDS_LIBRARAY_ACCOUNT')?></a> </li>
          <li> <a href="https://kim.uni-hohenheim.de/index.php?id=103170"><?=$this->transEsc('RDS_SYSTEMATIC_SEARCH')?></a> </li>
          <li> <a href="http://rzblx10.uni-regensburg.de/dbinfo/fachliste.php?bib_id=ubhoh&lett=l&colors=&ocolors="><?=$this->transEsc('RDS_SUBJECT_DATABASES')?></a> </li>
          <li></li>
          <li> <a href="#" title="Impressum hohsearch"><?=$this->transEsc('RDS_IMPRINT')?></a> </li>
        </ul>
      </div>
      <div class="footer-right col-sm-6 col-md-8 col-lg-6">
        <h4><?=$this->transEsc('RDS_UNIVERSITY_OF_HOHENHEIM')?></h4>
        <p><?=$this->transEsc('RDS_COMMUNICATION_INFORMATION_AND_MEDIACENTER')?><br>
          D-70593 Stuttgart <br>
          <a href="https://kim.uni-hohenheim.de" title="<?=$this->transEsc('RDS_HOMPAGE_KIM_TITLE')?>" target="_blank">kim.uni-hohenheim.de</a> </p>
        <div class="row">
          <div class="col-md-4">
            <h4><?=$this->transEsc('RDS_CENTRAL_LIBRARY')?></h4>
            <p><?=$this->transEsc('RDS_CIRCULATION_COUNTER')?>: <a href="tel:+4971145922097" title="<?=$this->transEsc('RDS_CENTRAL_LIBRARY_CIRCULATION_COUNTER_TITLE')?>">0711/459-22097</a> <br>
              <?=$this->transEsc('RDS_INFORMATION')?>: <a href="tel:+4971145922096" title="<?=$this->transEsc('RDS_CENTRAL_LIBRARY_INFORMATION_TITLE')?>">0711/459-22096</a> <br>
              <a href="mailto:kim-bib@uni-hohenheim.de" title="<?=$this->transEsc('RDS_CENTRAL_LIBRARY_EMAIL_TITLE')?>">kim-bib@uni-hohenheim.de</a> </p>
          </div>
          <div class="col-md-4">
            <h4><?=$this->transEsc('RDS_DEPARTMENTAL_LIBRARY')?></h4>
            <p><?=$this->transEsc('RDS_CIRCULATION_COUNTER')?>: <a href="tel:+4971145922068" title="<?=$this->transEsc('RDS_DEPARTMENTAL_LIBRARY_CIRCULATION_COUNTER_TITLE')?>">0711/459-22068</a> <br>
              <?=$this->transEsc('RDS_INFORMATION')?>: <a href="tel:+4971145924299" title="<?=$this->transEsc('RDS_DEPARTMENTAL_LIBRARY_INFORMATION_TITLE')?>">0711/459-24299</a> <br>
              <a href="mailto:kim-bib@uni-hohenheim.de" title="<?=$this->transEsc('RDS_DEPARTMENTAL_LIBRARY_EMAIL_TITLE')?>">kim-bib@uni-hohenheim.de</a> </p>
          </div>
          <div class="col-md-4">
            <h4><?=$this->transEsc('RDS_IT_SERVICE_DESK')?></h4>
            <p><?=$this->transEsc('RDS_PHONE')?>: <a href="tel:+4971145924444" title="<?=$this->transEsc('RDS_IT_SERVICE_DESK_INFORMATION_TITLE')?>">0711/459-24444 </a><br>
              <a href="mailto:kim-it@uni-hohenheim.de" title="<?=$this->transEsc('RDS_IT_SERVICE_DESK_EMAIL_TITLE')?>">kim-it@uni-hohenheim.de</a> </p>
          </div>
        </div>
      </div>
    </div>