    <div class="row">
      <div class="footer-left col-sm-6 col-md-4 col-lg-6">
        <ul class="list-unstyled">
          <li> <a href="https://hoh.ibs-bw.de/aDISWeb/app?service=direct/0/Home/$DirectLink&sp=S127.0.0.1:23022&sp=SBK00000000">Bibliothekskonto</a> </li>
          <li> <a href="https://kim.uni-hohenheim.de/index.php?id=103170">Systhematische Suche</a> </li>
          <li> <a href="http://rzblx10.uni-regensburg.de/dbinfo/fachliste.php?bib_id=ubhoh&lett=l&colors=&ocolors=">Fachdatenbanken</a> </li>
          <li></li>
          <li> <a href="#" title="Impressum hohsearch">Impressum</a> </li>
        </ul>
      </div>
      <div class="footer-right col-sm-6 col-md-8 col-lg-6">
        <h4>Universität Hohenheim (630)</h4>
        <p>Kommunikations-, Informations- und Medienzentrum <br>
          D-70593 Stuttgart <br>
          <a href="https://kim.uni-hohenheim.de" title="Homepage KIM" target="_blank">kim.uni-hohenheim.de</a> </p>
        <div class="row">
          <div class="col-md-4">
            <h4>Zentralbibliothek</h4>
            <p>Ausleihe: <a href="tel:+4971145922097" title="Telefon KIM Zentralbibliothek Ausleihe">0711/459-22097</a> <br>
              Information: <a href="tel:+4971145922096" title="Telefon KIM Zentralbibliothek Information">0711/459-22096</a> <br>
              <a href="mailto:kim-bib@uni-hohenheim.de" title="Mailadresse KIM Bibliothek">kim-bib@uni-hohenheim.de</a> </p>
          </div>
          <div class="col-md-4">
            <h4>Bereichsbibliothek</h4>
            <p>Ausleihe: <a href="tel:+4971145922068" title="Telefon KIM Bereichsbibliothek Ausleihe">0711/459-22068</a> <br>
              Information: <a href="tel:+4971145924299" title="Telefon KIM Bereichsbibliothek Information">0711/459-24299</a> <br>
              <a href="mailto:kim-bib@uni-hohenheim.de" title="Mailadresse KIM Bibliothek">kim-bib@uni-hohenheim.de</a> </p>
          </div>
          <div class="col-md-4">
            <h4>IT-Service-Desk</h4>
            <p>Telefon: <a href="tel:+4971145924444" title="Telefon KIM IT-Service-Desk">0711/459-24444 </a><br>
              <a href="mailto:kim-it@uni-hohenheim.de" title="Mailadresse KIM IT-Service-Desk">kim-it@uni-hohenheim.de</a> </p>
          </div>
        </div>
      </div>
    </div>
